import OpenAI from 'openai'; import { z } from 'zod'; import type { ChangeImpact, Evidence, Scenario, SourceArtifact } from '@testgen/core';
const ScenarioSchema=z.object({title:z.string(),layer:z.enum(['ui','api']),priority:z.enum(['P0','P1','P2']),riskScore:z.number().min(0).max(100),riskReasons:z.array(z.string()).min(1),given:z.array(z.string()).min(1),when:z.array(z.string()).min(1),then:z.array(z.string()).min(1)});
const OutputSchema=z.object({coverageGaps:z.array(z.string()),scenarios:z.array(ScenarioSchema).min(1).max(12)});
export type ReasoningOutput=z.infer<typeof OutputSchema>;
export interface Reasoner { name:string; reason(input:{artifacts:SourceArtifact[];impact:ChangeImpact;evidence:Evidence[]}):Promise<ReasoningOutput|null> }
export class OpenAIReasoner implements Reasoner { name='openai'; private client:OpenAI; constructor(){this.client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});}
 async reason(input:{artifacts:SourceArtifact[];impact:ChangeImpact;evidence:Evidence[]}){const model=process.env.OPENAI_MODEL||'gpt-4o-mini'; const prompt=`You are a senior SDET risk-analysis agent. Produce ONLY JSON with coverageGaps and scenarios. Base every scenario on supplied evidence. Prioritize changed, revenue/security critical, negative, boundary, idempotency and historical-defect paths. Do not invent endpoints.\nIMPACT=${JSON.stringify(input.impact)}\nEVIDENCE=${JSON.stringify(input.evidence)}\nARTIFACTS=${JSON.stringify(input.artifacts.map(a=>({id:a.id,type:a.type,name:a.name,content:a.content.slice(0,1800)})))}`; const r=await this.client.chat.completions.create({model,messages:[{role:'user',content:prompt}],response_format:{type:'json_object'},temperature:0.1}); const raw=r.choices[0]?.message?.content; if(!raw)return null; return OutputSchema.parse(JSON.parse(raw)); }
}
export function codeFor(s:Omit<Scenario,'id'|'evidence'|'generatedCode'>):string {const title=s.title.replace(/'/g,"\\'"); if(s.layer==='ui')return `import { test, expect } from '@playwright/test';\n\ntest('${title}', async ({ page }) => {\n  await page.goto(process.env.APP_URL ?? '/');\n  // TODO: map evidence-backed page objects/locators for: ${s.when.join('; ')}\n  await expect(page).toHaveURL(/.+/);\n});`;
 return `import { test, expect } from '@playwright/test';\n\ntest('${title}', async ({ request }) => {\n  // TODO: map evidence-backed endpoint/payload for: ${s.when.join('; ')}\n  const response = await request.get('/health');\n  expect(response.ok()).toBeTruthy();\n});`;}
